/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package loginandsignup;

import java.awt.Component;
import java.awt.Container;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author LENOVO
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
        setActionCommands();
    }
    
  
    private void setActionCommands() {
        A.setActionCommand("A");
        B.setActionCommand("B");
        C.setActionCommand("C");
        D.setActionCommand("D");
    }
    private int questionNumber;

     public void setQuestionNumber(int questionNumber) {
        this.questionNumber = questionNumber;
    }
    public JRadioButton getA()
    {
        return A;
    }
    public JRadioButton getB()
    {
        return B;
    }
    public JRadioButton getC()
    {
        return C;
    }
    public JRadioButton getD()
    {
        return D;
    }
  
    public void setquestionno(String Text)
    {
        question.setText(Text);
       
    }
    public void setoption1(String Text)
    {
        option1.setText(Text);
        
    }
    public void setoption2(String Text)
    {
        option2.setText(Text);
       
    }
    public void setoption3(String Text)
    {
        option3.setText(Text);
       
    }
    public void setoption4(String Text)
    {
        option4.setText(Text);
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        A = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        option1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        option2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        option3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        option4 = new javax.swing.JTextArea();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        question.setColumns(20);
        question.setRows(5);
        jScrollPane1.setViewportView(question);

        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        option1.setColumns(20);
        option1.setRows(5);
        jScrollPane2.setViewportView(option1);

        option2.setColumns(20);
        option2.setRows(5);
        jScrollPane3.setViewportView(option2);

        option3.setColumns(20);
        option3.setRows(5);
        jScrollPane4.setViewportView(option3);

        option4.setColumns(20);
        option4.setRows(5);
        jScrollPane5.setViewportView(option4);

        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(A)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(C)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(D)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(249, 249, 249)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2)
                                        .addGap(11, 11, 11)))))
                        .addGap(125, 125, 125)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(D)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (question.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the question");
        } else if (option1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "option 1 is missing");
        } else if (option2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "option 2 is missing");
        } else if (option3.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "option 3 is missing");
        } else if (option4.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "option 4 is missing");
        } else {
            Quiz A1 = new Quiz();
            
            if (A.isSelected()) {
                String selectedOptionText = "A";
                Quiz1 q2 = new Quiz1();
                q2.Add_question(question.getText(), option1.getText(), option2.getText(), option3.getText(), option4.getText(),selectedOptionText , Quiz1.admin_id,Quiz1.quiz_ids);
            } else if (B.isSelected()) {
                String  selectedOptionText = "B";
                Quiz1 q2 = new Quiz1();
                q2.Add_question(question.getText(), option1.getText(), option2.getText(), option3.getText(), option4.getText(),selectedOptionText , Quiz1.admin_id,Quiz1.quiz_ids);
            } else if (C.isSelected()) {
                String  selectedOptionText = "C";
                Quiz1 q2 = new Quiz1();
                q2.Add_question(question.getText(), option1.getText(), option2.getText(), option3.getText(), option4.getText(),selectedOptionText ,Quiz1.admin_id,Quiz1.quiz_ids);
            } else if (D.isSelected()) {
                String  selectedOptionText = "D";
                Quiz1 q2 = new Quiz1();
                q2.Add_question(question.getText(), option1.getText(), option2.getText(), option3.getText(), option4.getText(),selectedOptionText , Quiz1.admin_id,Quiz1.quiz_ids);
            } else {
                JOptionPane.showMessageDialog(null, "Please select an option");
                return; // Exit the method if no option is selected
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        D.setActionCommand("D");
    }//GEN-LAST:event_DActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed

    }//GEN-LAST:event_CActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed

    }//GEN-LAST:event_BActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed

    }//GEN-LAST:event_AActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     Quiz1 q = new Quiz1();
     Add_question A1 = new Add_question();
     System.out.println(questionNumber);
     System.out.println(Quiz1.quiz_ids);
     System.out.println(Loginandsignup.name);
      
     q.deletequestions(questionNumber, Quiz1.quiz_ids,Loginandsignup.name);
    remove();
    A1.totalQuestions--;
//    for (int i = questionNumber + 1; i <= A1.totalQuestions; i++) {
//    // Get the panel representing the i-th question
//    Component[] components = A1.getComponents();
//    for (Component component : components) {
//        if (component instanceof NewJPanel) {
//            NewJPanel panel = (NewJPanel) component;
//            if (panel.getQuestionNumber() == i) {
//                // Update the question number of the panel
//                panel.setQuestionNumber(i - 1);
//                // Update the question label text if necessary
//                // panel.setQuestionLabelText("Question " + (i - 1)); 
//                break;
//            }
//        }
//    }}
        

    }//GEN-LAST:event_jButton2ActionPerformed
    private void removePanelAction() {
        Container parent = getParent();
        if (parent instanceof JPanel) {
            // Cast the parent to JPanel and remove this panel from it
            ((JPanel) parent).remove(NewJPanel.this);
            // Revalidate and repaint the parent panel (paper)
            parent.revalidate();
            parent.repaint();
        }
    }
    
    public void remove() {
        Container parent = getParent();
        if (parent instanceof JPanel) {
            int removedQuestionNumber = getQuestionNumber();
            ((JPanel) parent).remove(this);

            // Iterate over the remaining panels and update their question numbers
            Component[] components = parent.getComponents();
            for (Component component : components) {
                if (component instanceof NewJPanel) {
                    NewJPanel panel = (NewJPanel) component;
                    int panelQuestionNumber = panel.getQuestionNumber();
                    if (panelQuestionNumber > removedQuestionNumber) {
                        // Decrement the question number of subsequent panels
                        panel.setQuestionNumber(panelQuestionNumber - 1);
                        panel.setquestionno("Question " + (panelQuestionNumber - 1)); // Update question label
                    }
                }
            }

            parent.revalidate();
            parent.repaint();
        }
    }
    public int getQuestionNumber()
    {
        return questionNumber;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     if (question.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter the question");
    } else if (option1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "option 1 is missing");
    } else if (option2.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "option 2 is missing");
    } else if (option3.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "option 3 is missing");
    } else if (option4.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "option 4 is missing");
    } else {
        // Update the text in JTextArea components
        question.setText(question.getText().trim());
        option1.setText(option1.getText().trim());
        option2.setText(option2.getText().trim());
        option3.setText(option3.getText().trim());
        option4.setText(option4.getText().trim());

        // Create an instance of your database access class
        Quiz1 q2 = new Quiz1();

        // Determine the selected option
        String selectedOptionText = "";
        if (A.isSelected()) {
            selectedOptionText = "A";
        } else if (B.isSelected()) {
            selectedOptionText = "B";
        } else if (C.isSelected()) {
            selectedOptionText = "C";
        } else if (D.isSelected()) {
            selectedOptionText = "D";
        } else {
            JOptionPane.showMessageDialog(null, "Please select an option");
            return; // Exit the method if no option is selected
        }

        // Update the question in the database
        String quizId = Quiz1.quiz_ids;
        q2.updatequestions(question.getText(), option1.getText(), option2.getText(), option3.getText(), option4.getText(), selectedOptionText, Quiz1.admin_id, questionNumber, quizId);
    }


    }//GEN-LAST:event_jButton3ActionPerformed
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea option1;
    private javax.swing.JTextArea option2;
    private javax.swing.JTextArea option3;
    private javax.swing.JTextArea option4;
    private javax.swing.JTextArea question;
    // End of variables declaration//GEN-END:variables
}
