/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package loginandsignup;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author LENOVO
 */
public class Viewquestions extends javax.swing.JPanel {
public boolean submitted(boolean submitted)
{
    return submitted;
}
    /**
     * Creates new form Viewquestions
     */
    public Viewquestions() {
        initComponents();
        setActionCommands();
        
    }
      private int qno;
    public void setqno(int qno)
    {
        this.qno = qno;
    }
    
    private void setActionCommands() {
        A.setActionCommand("A");
        B.setActionCommand("B");
        C.setActionCommand("C");
        D.setActionCommand("D");
    }
    public JRadioButton getA()
    {
        return A;
    }
    public JRadioButton getB()
    {
        return B;
    }
    public JRadioButton getC()
    {
        return C;
    }
    public JRadioButton getD()
    {
        return D;
    }
    public void setquestionno(String Text)
    {
        question.setText(Text);
    }
    public void setoption1(String Text)
    {
        option1.setText(Text);
    }
    public void setoption2(String Text)
    {
        option2.setText(Text);
    }
    public void setoption3(String Text)
    {
        option3.setText(Text);
    }
    public void setoption4(String Text)
    {
        option4.setText(Text);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        A = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        option1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        option2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        option3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        option4 = new javax.swing.JTextArea();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        question.setEditable(false);
        question.setColumns(20);
        question.setRows(5);
        question.setText("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
        jScrollPane1.setViewportView(question);

        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        option1.setEditable(false);
        option1.setColumns(20);
        option1.setRows(5);
        jScrollPane2.setViewportView(option1);

        option2.setEditable(false);
        option2.setColumns(20);
        option2.setRows(5);
        jScrollPane3.setViewportView(option2);

        option3.setEditable(false);
        option3.setColumns(20);
        option3.setRows(5);
        jScrollPane4.setViewportView(option3);

        option4.setEditable(false);
        option4.setColumns(20);
        option4.setRows(5);
        jScrollPane5.setViewportView(option4);

        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(A))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(B)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(C)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(D)
                        .addGap(8, 8, 8)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
    if(A.isSelected())
    { 
        System.out.println(Loginandsignup.name);
        System.out.println(user.studusername);
        System.out.println(qno);
        
        String SlectedoptionText = "A";
        System.out.println(SlectedoptionText);
        submitted(true);
        user.optionSelected(Quizzes_for_user.ids,Loginandsignup.name ,qno,user.studusername  , SlectedoptionText);
        setRadioButtonsEnabled(false);
    }
    }//GEN-LAST:event_AActionPerformed
   public void setRadioButtonsEnabled(boolean enabled) {
    A.setEnabled(enabled);
    B.setEnabled(enabled);
    C.setEnabled(enabled);
    D.setEnabled(enabled);
}
    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
       if(B.isSelected())
    {
        submitted(true);
        String SlectedoptionText = "B";
        user.optionSelected(Quizzes_for_user.ids,Loginandsignup.name ,qno,user.studusername  , SlectedoptionText);
         
        setRadioButtonsEnabled(false);
    }
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
           if(C.isSelected())
    {
        submitted(true);
        String SlectedoptionText = "C";
        user.optionSelected(Quizzes_for_user.ids,Loginandsignup.name ,qno,user.studusername  , SlectedoptionText);
        setRadioButtonsEnabled(false);
    }
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
          if(D.isSelected())
    {
        submitted(true);
        String SlectedoptionText = "D";
        user.optionSelected(Quizzes_for_user.ids,Loginandsignup.name ,qno,user.studusername  , SlectedoptionText);
        setRadioButtonsEnabled(false);
    }
    }//GEN-LAST:event_DActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea option1;
    private javax.swing.JTextArea option2;
    private javax.swing.JTextArea option3;
    private javax.swing.JTextArea option4;
    private javax.swing.JTextArea question;
    // End of variables declaration//GEN-END:variables
}
